version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - default

  frontend:
    image: frontend:latest
    container_name: frontend
    build: course-management-frontend
    restart: always
    ports:
      - "80:3000"
    networks:
      - default
    depends_on:
      - mongo

  backend:
    image: backend:latest
    container_name: backend
    build: course-management-backend
    restart: always
    ports:
      - "5000:5000"
    networks:
      - default
    depends_on:
      - mongo

volumes:
  mongo-data:

networks:
  docker-network:
    driver: bridge

