# docker  for nestjs backend

# base image
FROM node:20

# set working directory
WORKDIR /usr/src/app

# copy package.json

COPY package*.json ./

# install dependencies

RUN npm install

# copy source code

COPY . .

# expose port 3000

EXPOSE 5000

# build and run the app

CMD ["npm", "run", "start"]