# docker  for nextjs frontend

# base image

FROM node:20


# set working directory

WORKDIR /usr/src/app

# copy package.json

COPY package*.json ./

# install dependencies

RUN npm install

# copy source code

COPY . .

# expose port 3000

EXPOSE 3000

# build app 

RUN npm run build

# run the app

CMD ["npm", "run", "start"]